### ISSUE TITLE
spark_master.out logfile prevents shared installation

### ISSUE THREAD

**Issue by dschulzg** [rokroskar/sparkhpc#15]
The spark_master.out logfile is hardcoded as $SPARK_HOME/logs/spark_master.out.  This prevents shared installations accessible by multiple users as the first user to write the spark_master.out file owns it and prevents others from writing there.  I propose changing to $USER_HOMEDIR/.sparkhpc/logs.

**Comment by dschulzg** [comment]
I figured out how to do a pull request.  See  #16

**Comment by rokroskar** [comment]
Thanks for opening the issue -- I'll keep it open until the PR is merged
